// The CMS Americas Advanced Sommelier core grapes come first — they are the majority of what is
// poured in the exam — then other classic varieties that can appear as "classic" wines.
export const GRAPE_VARIETALS = [
	// Core — white
	'Albariño',
	'Chardonnay',
	'Chenin Blanc',
	'Gewürztraminer',
	'Grüner Veltliner',
	'Pinot Gris/Pinot Grigio',
	'Riesling',
	'Sauvignon Blanc',
	'Torrontés',
	'Viognier',
	// Core — red
	'Cabernet Sauvignon',
	'Cabernet Franc',
	'Carménère',
	'Corvina',
	'Gamay',
	'Grenache',
	'Malbec',
	'Merlot',
	'Nebbiolo',
	'Pinot Noir',
	'Sangiovese',
	'Syrah/Shiraz',
	'Tempranillo',
	'Zinfandel/Primitivo',
	// Other classic — white
	'Sémillon',
	'Muscat',
	'Marsanne',
	'Roussanne',
	'Melon de Bourgogne',
	'Pinot Blanc',
	'Verdejo',
	'Godello',
	'Assyrtiko',
	'Furmint',
	'Vermentino',
	'Garganega',
	'Fiano',
	'Greco',
	'Trebbiano',
	'Arneis',
	'Cortese',
	// Other classic — red
	'Mourvèdre/Monastrell',
	'Petit Verdot',
	'Carignan',
	'Cinsault',
	'Petite Sirah',
	'Barbera',
	'Dolcetto',
	'Aglianico',
	'Montepulciano',
	'Nerello Mascalese',
	'Nero d’Avola',
	'Touriga Nacional',
	'Blaufränkisch',
	'Xinomavro',
	'Pinotage',
	'Tannat',
];

export const WINE_REGIONS = [
	// France — Bordeaux
	'Bordeaux',
	'Médoc',
	'Haut-Médoc',
	'Pauillac',
	'Margaux',
	'Saint-Julien',
	'Saint-Estèphe',
	'Pessac-Léognan',
	'Graves',
	'Saint-Émilion',
	'Pomerol',
	'Fronsac',
	'Sauternes',
	'Barsac',
	// France — Burgundy
	'Burgundy',
	'Chablis',
	'Côte de Nuits',
	'Côte de Beaune',
	'Côte Chalonnaise',
	'Mâconnais',
	"Côte d'Or",
	'Beaujolais-Villages',
	'Cru Beaujolais',
	'Gevrey-Chambertin',
	'Chambolle-Musigny',
	'Morey-Saint-Denis',
	'Vosne-Romanée',
	'Nuits-Saint-Georges',
	'Aloxe-Corton',
	'Beaune',
	'Pommard',
	'Volnay',
	'Meursault',
	'Puligny-Montrachet',
	'Chassagne-Montrachet',
	'Pouilly-Fuissé',
	'Saint-Véran',
	'Mercurey',
	'Givry',
	// France — Rhône
	'Northern Rhône',
	'Southern Rhône',
	'Côte-Rôtie',
	'Hermitage',
	'Crozes-Hermitage',
	'Cornas',
	'Saint-Joseph',
	'Condrieu',
	'Châteauneuf-du-Pape',
	'Gigondas',
	'Vacqueyras',
	'Lirac',
	'Tavel',
	'Côtes du Rhône Villages',
	// France — Loire
	'Loire Valley',
	'Sancerre',
	'Pouilly-Fumé',
	'Muscadet',
	'Vouvray',
	'Montlouis',
	'Chinon',
	'Saumur-Champigny',
	'Montlouis-sur-Loire',
	'Bourgueil',
	'Saint-Nicolas-de-Bourgueil',
	'Savennières',
	'Anjou',
	'Touraine',
	// France — Alsace, Champagne, Other
	'Alsace',
	'Champagne',
	'Provence',
	'Bandol',
	'Cassis',
	'Languedoc',
	'Roussillon',
	'Pic Saint-Loup',
	'Faugères',
	'Saint-Chinian',
	'Minervois',
	'Cahors',
	'Madiran',
	'Jurançon',
	'Bergerac',
	// Italy — Piedmont
	'Piedmont',
	'Barolo',
	'Barbaresco',
	"Barbera d'Asti",
	"Barbera d'Alba",
	"Dolcetto d'Alba",
	'Gavi',
	"Moscato d'Asti",
	'Asti Spumante',
	'Roero',
	'Langhe',
	// Italy — Tuscany
	'Tuscany',
	'Chianti',
	'Chianti Classico',
	'Brunello di Montalcino',
	'Rosso di Montalcino',
	'Vino Nobile di Montepulciano',
	'Morellino di Scansano',
	'Bolgheri',
	'Maremma',
	'Vernaccia di San Gimignano',
	'Carmignano',
	// Italy — Other
	'Friuli',
	'Trentino-Alto Adige',
	'Veneto',
	'Amarone della Valpolicella',
	'Valpolicella',
	'Ripasso',
	'Soave',
	'Bardolino',
	'Prosecco',
	'Valdobbiadene',
	'Friuli-Venezia Giulia',
	'Alto Adige',
	'Trentino',
	'Lombardy',
	'Franciacorta',
	'Valtellina',
	'Campania',
	'Taurasi',
	'Fiano di Avellino',
	'Greco di Tufo',
	'Sicily',
	'Etna',
	'Marsala',
	"Nero d'Avola",
	'Puglia',
	'Primitivo di Manduria',
	'Salento',
	'Negroamaro',
	'Umbria',
	'Sagrantino di Montefalco',
	'Orvieto',
	'Sardinia',
	'Vermentino di Sardegna',
	// Spain
	'Rioja',
	'Rioja Alta',
	'Rioja Alavesa',
	'Rioja Oriental',
	'Ribera del Duero',
	'Priorat',
	'Montsant',
	'Rías Baixas',
	'Rueda',
	'Toro',
	'Navarra',
	'Penedès',
	'Cava',
	'Jerez',
	'Manzanilla',
	'Bierzo',
	'Jumilla',
	'Yecla',
	'Calatayud',
	// Germany
	'Mosel',
	'Saar',
	'Ruwer',
	'Rheingau',
	'Rheinhessen',
	'Pfalz',
	'Nahe',
	'Franken',
	'Baden',
	'Württemberg',
	'Ahr',
	'Mittelrhein',
	// Portugal
	'Douro',
	'Port',
	'Dão',
	'Bairrada',
	'Alentejo',
	'Vinho Verde',
	'Setúbal',
	'Lisboa',
	'Tejo',
	'Algarve',
	'Madeira',
	// USA — California
	'Napa Valley',
	'Sonoma County',
	'Central Coast',
	'Anderson Valley',
	'Rutherford',
	'Oakville',
	'Stags Leap District',
	'Carneros',
	'Howell Mountain',
	'Mount Veeder',
	'Spring Mountain',
	'Diamond Mountain',
	'Calistoga',
	'Coombsville',
	'Sonoma',
	'Alexander Valley',
	'Dry Creek Valley',
	'Russian River Valley',
	'Sonoma Coast',
	'Sonoma Valley',
	'Knights Valley',
	'Rockpile',
	'Santa Barbara',
	'Santa Ynez Valley',
	'Sta. Rita Hills',
	'Happy Canyon',
	'Paso Robles',
	'Santa Cruz Mountains',
	'Livermore Valley',
	'Lodi',
	'Sierra Foothills',
	// USA — Oregon & Washington
	'Willamette Valley',
	'Dundee Hills',
	'Chehalem Mountains',
	'Eola-Amity Hills',
	'Columbia Valley',
	'Walla Walla Valley',
	'Yakima Valley',
	'Red Mountain',
	'Horse Heaven Hills',
	// Australia
	'South Australia',
	'Victoria',
	'Western Australia',
	'Adelaide Hills',
	'Barossa Valley',
	'Eden Valley',
	'Clare Valley',
	'McLaren Vale',
	'Coonawarra',
	'Yarra Valley',
	'Mornington Peninsula',
	'Heathcote',
	'Grampians',
	'Margaret River',
	'Great Southern',
	'Hunter Valley',
	'Mudgee',
	'Rutherglen',
	'Tasmania',
	// New Zealand
	'Marlborough',
	'Central Otago',
	"Hawke's Bay",
	'Martinborough',
	'Nelson',
	'Waipara',
	// Argentina
	'Mendoza',
	'Luján de Cuyo',
	'Maipú',
	'Valle de Uco',
	'Tupungato',
	'Salta',
	'Cafayate',
	'Patagonia',
	'Neuquén',
	'Río Negro',
	// Chile
	'Maipo Valley',
	'Maipo',
	'Curicó',
	'Maule',
	'Rapel',
	'Colchagua Valley',
	'Casablanca Valley',
	'Aconcagua',
	'Leyda Valley',
	'San Antonio Valley',
	'Cachapoal Valley',
	'Maule Valley',
	'Biobío',
	'Elqui Valley',
	// South Africa
	'Stellenbosch',
	'Franschhoek',
	'Paarl',
	'Swartland',
	'Walker Bay',
	'Hemel-en-Aarde',
	'Constantia',
	'Elgin',
	'Robertson',
	// Austria
	'Wachau',
	'Kamptal',
	'Kremstal',
	'Wagram',
	'Traisental',
	'Burgenland',
	'Neusiedlersee',
	'Leithaberg',
	'Südsteiermark',
	'Weststeiermark',
	// Greece, Hungary, Georgia, Other
	'Santorini',
	'Naoussa',
	'Nemea',
	'Cephalonia',
	'Drama',
	'Patras',
	'Tokaj',
	'Eger',
	'Villány',
	'Szekszárd',
	'Kakheti',
	'Kartli',
	'Racha-Lechkhumi',
	'Douro Superior',
	'Finger Lakes',
	'Long Island',
	'Virginia',
];

export const WINE_COUNTRIES = [
	'France',
	'Italy',
	'Spain',
	'Germany',
	'Portugal',
	'Austria',
	'Greece',
	'Hungary',
	'United States',
	'Australia',
	'New Zealand',
	'Argentina',
	'Chile',
	'South Africa',
	'Canada',
	'Georgia',
	'Israel',
	'Lebanon',
	'Switzerland',
	'Romania',
	'Bulgaria',
	'Croatia',
	'Slovenia',
	'Uruguay',
];
