export const GRAPE_VARIETALS = [
  "Cabernet Sauvignon",
  "Merlot",
  "Pinot Noir",
  "Syrah/Shiraz",
  "Grenache",
  "Tempranillo",
  "Sangiovese",
  "Nebbiolo",
  "Malbec",
  "Zinfandel",
  "Gamay",
  "Mourvèdre",
  "Chardonnay",
  "Sauvignon Blanc",
  "Riesling",
  "Pinot Grigio/Pinot Gris",
  "Gewürztraminer",
  "Viognier",
  "Chenin Blanc",
  "Sémillon",
  "Muscat",
  "Grüner Veltliner",
  "Albariño",
  "Torrontés",
];

export const WINE_COUNTRIES = [
  "France",
  "Italy",
  "Spain",
  "Germany",
  "Portugal",
  "Austria",
  "Greece",
  "Hungary",
  "United States",
  "Australia",
  "New Zealand",
  "Argentina",
  "Chile",
  "South Africa",
  "Canada",
  "Georgia",
  "Israel",
  "Lebanon",
  "Switzerland",
  "Romania",
  "Bulgaria",
  "Croatia",
  "Slovenia",
  "Uruguay",
];
