version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: blind_tasting_db
    environment:
      POSTGRES_USER: marisha
      POSTGRES_PASSWORD: password
      POSTGRES_DB: blind_tasting
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:

